### ISSUE TITLE
Add support .NET Standard

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#111]
I've ran an analysis of the library (https://github.com/microsoft/dotnet-apiport) to determine what needs to be done in order to support .NET Standard (and by extension, .NET Core, UWP, etc). The following are the steps that need to be done for this:

- [x] Remove custom System.IO.Packaging (rely on built-in or use the build from CoreFX) (see #112)
- [x] Move to project.json (for multitargeting to .NET Standard 1.3 and .NET 4.5) (#115)
- [x] Update XML related issues (such as no XmlTextWriter) (see #113)
- [x] Replace unsupported types (such as StringCollection and CollectionBase) (see #114, #121)
- [x] Update usage of reflection to use TypeInfo instead of Type (#116, #121)
- [x] Get test suite compatible with .NET Standard (#120, #122 )
- [x] Replace BinaryFormatter (#117, #124)

There may be more, but this is a start from looking at the code base and the portability analyzer.

**Comment by ph1ll** [comment]
Very good to see some movement on this repo, I was starting to think it had been abandoned. 

I do have a working netstandard1.4 fork at https://github.com/ph1ll/Open-XML-SDK/tree/netstandard, which I use internally. The main problem with porting at the moment is the lack of BinaryFormatter - I worked around this by using protobuf-net and adding a tool to convert the existing serialised schema files - very messy hence not submitting a MR for the changes. 

I think the best option would be to replace the serialised schema files entirely, unfortunately the original generation code does not seem to be part of this repo, see #101. @twsouthwick if you can get hold of this generation code, I think it will make your life much easier. 

Please let me know if I can be of any help.

**Comment by twsouthwick** [comment]
Thanks @ph1ll! I recently found where that code generation is and that is definitely the hardest thing about  getting this working on .NET Standard. I initially did something similar to you, but serialized it to C# code so no deserialization was needed at runtime, but hooking into the actual code generation will be the best for long term support. For now, the goal is to get everything else in working order before tackling that aspect of the port. 

Feel free to submit any of the patches you've done to support .NET Standard!

btw, Why did you go for .NET Standard 1.4 instead of 1.3? I'm assuming to ease the porting of some reflection based changes, but maybe I missed something when I was analyzing the project.

**Comment by ph1ll** [comment]
I think the main reason for picking .NET Standard 1.4 was that I was targeting UWP and needed something working quickly. 

I will try and help out if I can, but given the number of MRs you already have underway, I have a feeling you will beat me to most bits. Many thanks for bringing some life back to the repo.

**Comment by ph1ll** [comment]
Awesome. Many thanks.
