### ISSUE TITLE
Organize test infrastructure

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#166]
The tests need to be cleaned up in order to decrease run time (such as is shown in #186). Things that need to be done:

- [x] Remove test context - this is unused and appears to be a remnant of an old test system (#231)
- [x] Use xunit's ITestOutputHelper instead of creating custom log files (#230)
- [x] Move test assets to be under the test directory so they can more easily be included in output using built-in tasks (#229)
- [x] Consolidate OpenXmlDomTestExtensions - these seem to be duplicated and structured in a way so there is no single point where a file is opened. In order to speed up tests, this needs to be consolidated (#228)
- [x] Redo "Safelist.xml" comparisons. This uses many regex comparisons to search for known issues and drastically slows the tests down (see https://github.com/OfficeDev/Open-XML-SDK/blob/vNext/DocumentFormat.OpenXml.Tests/OpenXmlDomTaskLibrary/OpenXmlDomTaskLibrary.cs#L40-L73)
- [x] Use embedded resources instead of flat files so that open operations can be done in-memory instead of via file paths. File IO is a huge bottleneck for these tests.
  - [x] Use test assets for `CreateDocumentTestClass` (#395)
  - [x] Use test assets for `DocumentTraverseTests.Traverse[xxx]Document` (#403)
  - [x] Use test assets for `GenerateList4LowLevelTest` (#405)
  - [x] Use test assets for `MarkupCompatibilityTest` (#414)
  - [x] Use test assets for `OpenXmlCompositeElementTestClass` (#402)
  - [x] Use test assets for `OpenXmlReaderWriterTest.[bug247883|bug251835_ReaderDispose]` (#404)
  - [x] Use test assets for `OpenXmlRootElementTestClass` (#397)
- [x] Create a test assets library to minimize compilation times
- [x] Remove current test util helpers that generate files (#443)
- [ ] Remove `VerifiableLog` and use `ITestOutputHelper`
- [ ] Move large generated tests to new assembly
